name: build-and-deploy-python3.8-with-dependencies

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["build-and-deploy-docker-python3.9-image"]
    types:
      - completed
  push:
    paths:
      - 'python3.9-with-dependencies/Dockerfile'
      - 'python3.9-with-dependencies/pyproject.toml'
      - 'python3.9-with-dependencies/poetry.lock'

jobs:
  build-python38-with-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build the image
        run: |
          docker buildx build --push --tag micwittmann/data-analysis-environment:python3.9-with-dependencies --platform linux/amd64 python3.9-with-dependencies/.